### ISSUE TITLE
位置情報機能が不完全

### ISSUE THREAD

**Issue by kein1592** [enpitut/ITW#5]
以下の環境で実行したところ、MainActivityの位置情報機能のビルドが通りませんでした。
対象端末:304SH(Android 4.4)
開発環境:Android Studio 1.4

具体的なMainActivityファイル内のエラーのメッセージは以下の通りです
・エラー箇所
onResumeメソッド内のloc.requestLocationUpdates(LocationManager.NETWORK_PROVIDER, 5000, 1, this);および
onDestroyメソッド内のloc.removeUpdates(this);
・エラーメッセージ
Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with `checkPermission`) or explicitly handle a potential `SecurityException`

解決方法としては、Android6以降を対象とする場合には下記のようにすればよいのですが、4.4の場合は対処法がわからない状態です。
http://stackoverflow.com/questions/32715189/location-manager-remove-updates-permission

**Comment by kein1592** [comment]
下記の条件分岐を付け加え、パーミッションの確認をするようにしたらビルドが通り、実機でも位置情報を取得することが可能になりました。
if(loc != null) {
            if (ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED
                    || ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED) {

**Comment by chiemi627** [comment]
:+1:
